name: Create Q4 Archive with Date

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  create-q4-archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create archive with Q4.java source code
      run: |
        DATE=$(date '+%d-%m-%Y')
        ARCHIVE_FILE="Q4_archive_${DATE}.txt"
        echo "Nom et prénom: Capucine" > $ARCHIVE_FILE
        echo "" >> $ARCHIVE_FILE
        echo "Contenu de Q4.java:" >> $ARCHIVE_FILE
        echo "-------------------" >> $ARCHIVE_FILE
        if [ -f "Q4.java" ]; then
          cat Q4.java >> $ARCHIVE_FILE
        else
          echo "Q4.java not found." >> $ARCHIVE_FILE
          exit 1
        fi

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Pull remote changes
      run: |
        git pull origin main --rebase || git reset --hard origin/main

    - name: Commit changes
      run: |
        git add Q4_archive_*.txt
        git commit -m "Create Q4_archive_<date>.txt with Q4.java source code" || echo "No changes to commit"

    - name: Push changes
      run: |
        git push origin main
